Add friends likes. 10 спринт
AlexandraLesnykh/java-filmorate2 pull request #1
Opened 2022-12-03 20:01 UTC by AlexandraLesnykh

2022-12-03 20:03 UTC, AlexandraLesnykh commented
Проект 10 спринта. 1 итерация.

2022-12-03 21:11 UTC, db-exp requested changes

2022-12-03 21:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final InMemoryFilmStorage inMemoryFilmStorage;
Тип должен быть просто FilmStorage

2022-12-03 21:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film create(@RequestBody Film film) throws ValidationException {
Valid лучше сюда вернуть

2022-12-03 21:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film update(@RequestBody Film film) throws ValidationException {
Valid лучше сюда вернуть

2022-12-03 21:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final InMemoryUserStorage inMemoryUserStorage;
Просто UserStorage тип должен быть

2022-12-03 21:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User create(@RequestBody User user) throws ValidationException {
Valid лучше сюда вернуть

2022-12-03 21:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User update(@RequestBody User user) throws ValidationException {
Valid лучше сюда вернуть

2022-12-03 21:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>  public class User {
нужно для полей добавить модификатор private

2022-12-03 21:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>  public class Film {
нужно для полей добавить модификатор private

2022-12-03 21:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    String name;
У name есть ограничения валидации?

2022-12-03 21:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final InMemoryFilmStorage inMemoryFilmStorage;
Должно быть просто FilmStorage

2022-12-03 21:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } catch (ObjectNotFoundException exception) {
кажется, что нет особо смысла еще раз перекладывать в такое же исключение

2022-12-03 21:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } catch (ActionHasAlreadyDoneException exception) {
кажется, что нет особо смысла еще раз перекладывать в такое же исключение

2022-12-03 21:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } catch (ObjectNotFoundException exception) {
кажется, что нет особо смысла еще раз перекладывать в такое же исключение

2022-12-03 21:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final InMemoryUserStorage inMemoryUserStorage;
Просто UserStorage

2022-12-03 21:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        } catch (ObjectNotFoundException exception) {
кажется, что нет особо смысла еще раз перекладывать в такое же исключение

2022-12-03 21:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        } catch (ActionHasAlreadyDoneException exception) {
такой же вопрос - а точно ли надо ловить и делать такие же ошибки?
У тебя выше они появляются правильно, по логике, а тут по факту - дублирование

2022-12-03 21:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        findUser(id).deleteFriend(friendId);
по идее надо и у друга удалять себя

2022-12-03 21:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            for (int i = 0; i < getFriendList(id).size(); i++) { //прохожусь по списку друзей i-го юзера
Можно взять два Set с друзьями у двух пользователей и вызывать https://docs.oracle.com/javase/7/docs/api/java/util/Set.html#retainAll(java.util.Collection)

2022-12-03 21:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        } catch (ValidationException validationException) {
тот же самый вопрос про try/catch как и выше в классах )

2022-12-03 21:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        } catch (ValidationException validationException) {
тот же самый вопрос про try/catch как и выше в классах )

2022-12-03 21:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        }catch (ValidationException validationException) {
тот же самый вопрос про try/catch как и выше в классах )

2022-12-03 21:11 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        } catch (ValidationException exception){
тот же самый вопрос про try/catch как и выше в классах )

2022-12-04 10:51 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final InMemoryFilmStorage inMemoryFilmStorage;
Исправлено

2022-12-04 10:53 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film create(@RequestBody Film film) throws ValidationException {
Исправлено

2022-12-04 10:53 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film update(@RequestBody Film film) throws ValidationException {
Исправлено

2022-12-04 10:54 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final InMemoryUserStorage inMemoryUserStorage;
Исправлено

2022-12-04 10:54 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User create(@RequestBody User user) throws ValidationException {
Исправлено

2022-12-04 10:54 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User update(@RequestBody User user) throws ValidationException {
Исправлено

2022-12-04 10:56 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>  public class User {
Исправлено

2022-12-04 10:56 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>  public class Film {
Исправлено

2022-12-04 11:04 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    String name;
Из ТЗ9: "имя для отображения может быть пустым — в таком случае будет использован логин". Соответственно ответ - нет, ограничения валидации нет. А Optional я использовала, чтобы уйти от NPE при проверке имени на пустоту.

2022-12-04 11:04 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final InMemoryFilmStorage inMemoryFilmStorage;
Исправлено

2022-12-04 11:05 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final InMemoryUserStorage inMemoryUserStorage;
Исправлено

2022-12-04 11:06 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        findUser(id).deleteFriend(friendId);
Согласна. Исправлено

2022-12-04 11:39 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } catch (ObjectNotFoundException exception) {
Нет ответа, почему я так сделала.. Поправила.

2022-12-04 11:39 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } catch (ActionHasAlreadyDoneException exception) {
Исправлено

2022-12-04 11:40 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } catch (ObjectNotFoundException exception) {
Исправлено

2022-12-04 11:40 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        } catch (ObjectNotFoundException exception) {
Исправлено

2022-12-04 11:40 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        } catch (ActionHasAlreadyDoneException exception) {
Исправлено

2022-12-04 11:40 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            for (int i = 0; i < getFriendList(id).size(); i++) { //прохожусь по списку друзей i-го юзера
Классная функция, спасибо! Исправлено

2022-12-04 11:40 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        } catch (ValidationException validationException) {
Исправлено

2022-12-04 11:40 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        } catch (ValidationException validationException) {
Исправлено

2022-12-04 11:41 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        }catch (ValidationException validationException) {
Исправлено

2022-12-04 11:41 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        } catch (ValidationException exception){
Исправлено

2022-12-04 12:24 UTC, AlexandraLesnykh commented
Проект 10 спринта. Итерация 2. Исправлено пробрасывание исключений. Изменено поле в контроллерах на интерфейс. Поля в моделях сделаны приватными.

2022-12-04 12:38 UTC, db-exp requested changes

2022-12-04 12:38 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
Storage лучше переместить в сервис, чтобы не смешивать слои

2022-12-04 12:38 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserStorage userStorage;
Storage лучше переместить в сервис, чтобы не смешивать слои

2022-12-04 12:51 UTC, db-exp requested changes

2022-12-04 12:51 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        } catch (ValidationException validationException) {
даже выкачал к себе на всякий, но вижу, что try/catch остался

2022-12-04 12:51 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        } catch (ValidationException validationException) {
try/catch остался

2022-12-04 12:51 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        }catch (ValidationException validationException) {
try/catch остался

2022-12-04 12:51 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        } catch (ValidationException exception){
try/catch остался

2022-12-04 18:22 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        } catch (ValidationException validationException) {
Моя вина. Поправила.

2022-12-04 18:22 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        } catch (ValidationException validationException) {
Поправила

2022-12-04 18:22 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        }catch (ValidationException validationException) {
Поправила

2022-12-04 18:22 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        } catch (ValidationException exception){
Поправила

2022-12-04 18:38 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
Сделано

2022-12-04 18:38 UTC, AlexandraLesnykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserStorage userStorage;
Сделано

2022-12-04 18:41 UTC, AlexandraLesnykh commented
Проект 10 спринта. Итерация 3. Удалены конструкции try/catch, убрана зависимость  контроллера от хранилища.

2022-12-04 18:57 UTC, db-exp approved these changes

2023-06-19 11:01 UTC, merged